version: '3'
services:
  php:
    image: nearmarket-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/web

  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/web
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - php

  db-nearmarket:
    build: ./docker/db
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'superpass'
    volumes:
      - bddata:/var/lib/mysql

volumes:
  bddata:
    driver: local

