version: "3"
services:
  node:
    image: node:10
    working_dir: "/var/www/app"
    volumes:
      - ./:/var/www/app
    command: bash -c "npm install && npm run serve"
    ports:
      - "8080:8080"